/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c2c6d6",
        "on-secondary": "#003640",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#002113",
        "surface-container": "#19202e",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-fixed": "#acedff",
        "on-primary": "#002e6a",
        "bg-panel": "#172033",
        "tertiary": "#4edea3",
        "success": "#10B981",
        "on-primary-fixed": "#001a42",
        "inverse-on-surface": "#2a3040",
        "on-error": "#690005",
        "surface": "#0c1321",
        "text-primary": "#F9FAFB",
        "primary-fixed-dim": "#adc6ff",
        "text-muted": "#9CA3AF",
        "inverse-surface": "#dce2f6",
        "on-secondary-fixed-variant": "#004e5c",
        "secondary": "#4cd7f6",
        "outline": "#8c909f",
        "bg-card": "#1F2937",
        "surface-bright": "#323949",
        "primary-container": "#4d8eff",
        "on-tertiary": "#003824",
        "bg-secondary": "#111827",
        "surface-container-low": "#151b2a",
        "on-primary-container": "#00285d",
        "surface-variant": "#2e3544",
        "surface-container-high": "#232a39",
        "secondary-fixed-dim": "#4cd7f6",
        "tertiary-container": "#00a572",
        "on-tertiary-container": "#00311f",
        "on-surface": "#dce2f6",
        "background": "#0c1321",
        "on-secondary-fixed": "#001f26",
        "surface-dim": "#0c1321",
        "warning": "#F59E0B",
        "text-secondary": "#D1D5DB",
        "outline-variant": "#424754",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-container": "#00424e",
        "on-primary-fixed-variant": "#004395",
        "primary": "#adc6ff",
        "error": "#EF4444",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-highest": "#2e3544",
        "surface-container-lowest": "#070e1c",
        "on-background": "#dce2f6",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#005ac2",
        "primary-fixed": "#d8e2ff",
        "surface-tint": "#adc6ff",
        "secondary-container": "#03b5d3"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "inner-padding": "1rem",
        "gutter": "1.5rem",
        "container-max": "1280px",
        "panel-gap": "1rem",
        "card-padding": "1.5rem"
      },
    },
  },
  plugins: [],
}
